# Generated by Django 5.0.3 on 2024-03-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_workoutsession_notes_alter_workoutsession_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutsession",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="workoutsession",
            name="duration",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
