# Generated by Django 5.0.3 on 2024-04-01 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "website",
            "0005_remove_goal_reps_remove_goal_sets_remove_goal_weight_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="muscle_groups",
            field=models.CharField(
                choices=[
                    ("chest", "chest"),
                    ("back", "back"),
                    ("arms", "arms"),
                    ("abdominals", "abdominals"),
                    ("legs", "legs"),
                    ("shoulders", "shoulders"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="workout",
            name="type",
            field=models.CharField(
                choices=[
                    ("Cardio", "Cardio"),
                    ("Strength Training", "Strength Training"),
                    ("Bodyweight", "Bodyweight"),
                    ("Flexibility and Balance", "Flexibility and Balance"),
                    ("Other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Bodyweight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.FloatField(max_length=1000)),
                (
                    "unit",
                    models.CharField(
                        choices=[("kg", "kg"), ("lbs", "lbs")], max_length=3
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CalorieIntake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calories", models.FloatField(max_length=100000)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
