# Generated by Django 5.0.3 on 2024-04-05 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0011_friendshiplist_delete_friendship"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="workout_session",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workout_session_rel_to_goal",
                to="website.workoutsession",
            ),
        ),
        migrations.AlterField(
            model_name="workout",
            name="workout_session",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workout_session_rel_to_workout",
                to="website.workoutsession",
            ),
        ),
        migrations.AlterField(
            model_name="workoutsession",
            name="goals",
            field=models.ManyToManyField(
                related_name="session_goals", to="website.goal"
            ),
        ),
        migrations.AlterField(
            model_name="workoutsession",
            name="workouts",
            field=models.ManyToManyField(
                related_name="session_workouts", to="website.workout"
            ),
        ),
    ]
